config/routes.rb
Rails.application.routes.draw do
  root 'character#index'
  get 'character/:id', to: 'character#show', as: :show_post
  delete "character/:id", to: 'character#destroy', as: :delete_post

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/character_controller.rb
class CharacterController < ApplicationController
  def index
    @character = Character.all
  end

  def show
    @character = Character.find(params[:id])
    render :show
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to root_path, notice: "Your post have been deleted!"
  end
end   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/views/character/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
 
    
    <div class="card-group">
        <% @character.each do |item| %>
          <div class="card card-1">
            <h3><%= item.name %></h3>
            <h1><%= item.age  %></h1>
              <div class="card-control">
             <%= link_to "Destroy",  delete_post_path(item), method: :delete, 
                data: {
                    confirm: "Are you sure you want to do this?"
                },
                class: "button-delete"
             %>
                <%= link_to "Show", show_post_path(item), class: "button-show"  %>
            </div>
          </div>
        <% end %>
    </div>

 
</body>
</html>

app/views/character/show.html.erb
<html>
    <body>
        <div class="card card-1">
            <p><%= @character.name %></p>
            <p><%= @character.age %></p>
            <div class="card-control">
                <%= link_to "Back", root_path, class: "button-back" %>
            </div>
        </div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <h1>Angelo everybody!</h1> 
   </div>
    <%= yield %>
  </body>
</html>